[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = master
last_revision = fd397fc751963d3585f52fa6f7048f30db258ffd

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = master
last_revision = c9b783f2e1d88bba59af2f609cb79a42c48d709b

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = 9e41c54b4558709f4ff20f03dad77f2cf99477ed

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = master
last_revision = 226839ac408223f8041cde1b1d8b762d6fbc8050

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = master
last_revision = 61bd265651b48486910343232c69c71b2b311f58

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = master
last_revision = ee6143138f1cd810669c4057df2b24efe6f46f1a

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = master
last_revision = 358519ca6406a89fee42c45dcaf63a37a374f33c

