[meta-arm]
src_uri = git://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = master
last_revision = 6182cec88cc5d177726d56d7fcea9f80e8f2786b

[meta-openembedded]
src_uri = git://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = master
last_revision = 2de5071f9ac17338ea8a0ec0bbd451c5455166e9

[meta-raspberrypi]
src_uri = git://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = 046a23892770accf32776bd16a2bf6ad534f42eb

[meta-security]
src_uri = git://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = master
last_revision = 06bd60600e8db1b843cf5cc0f074a11eac7e9a80

[openembedded-core]
src_uri = git://git.yoctoproject.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = master
last_revision = a59b385184fb3a548dc27310fd04d64351d8dfba

[bitbake]
src_uri = git://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = master
last_revision = b59bdcf8134e6f5935e8f7b0ed8033cbb745e0ff

[yocto-docs]
src_uri = git://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = master
last_revision = f9f1c87424d307d2df60024bc448bd6778605cf8

