[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = master
last_revision = 28606c721503b70e8343968731a24260cfe985bc

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = master
last_revision = e93799db0e7c7b23da8a00891403425ae7e87d7b

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = b0f0a6c0bfbf5d0e464c13944dda73fa69f31f6b

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = master
last_revision = 226839ac408223f8041cde1b1d8b762d6fbc8050

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = master
last_revision = 171af3b2915dd076c8d1b205ff75eac1ebd5a586

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = master
last_revision = 2c236d8bdc51742cbc5a97e30fb126d82d4a908a

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = master
last_revision = 358519ca6406a89fee42c45dcaf63a37a374f33c

